import { Question } from '@/types';

export const FALLBACK_QUESTIONS: Question[] = [
  {
    id: 'fb-01',
    question: '夏天被蚊虫叮咬后，最科学的做法是？',
    options: ['A. 用唾液涂抹止痒', 'B. 用肥皂水清洗后冷敷', 'C. 立即用手抓挠破皮', 'D. 涂抹酱油消毒'],
    answer: 'B',
    difficulty: 2,
    explanation: '肥皂水能中和蚁酸，冷敷可缓解肿胀瘙痒。抓挠会导致感染。',
  },
  {
    id: 'fb-02',
    question: '以下哪种食物最容易导致食物中毒？',
    options: ['A. 未煮熟的四季豆', 'B. 新鲜苹果', 'C. 白米饭', 'D. 煮熟的土豆'],
    answer: 'A',
    difficulty: 2,
    explanation: '未煮熟的四季豆含有皂苷和血球凝集素，食用后会引起恶心、呕吐、腹泻等中毒症状。',
  },
  {
    id: 'fb-03',
    question: '遇到火灾时，正确的逃生方式是？',
    options: ['A. 乘坐电梯快速下楼', 'B. 用湿毛巾捂口鼻弯腰前进', 'C. 躲在衣柜里等待救援', 'D. 打开窗户跳楼逃生'],
    answer: 'B',
    difficulty: 1,
    explanation: '火灾时电梯可能断电，浓烟向上聚集，弯腰并用湿毛巾捂住口鼻可减少吸入有毒烟气。',
  },
  {
    id: 'fb-04',
    question: '每天最佳睡眠时长大约是？',
    options: ['A. 4-5小时', 'B. 7-8小时', 'C. 10-12小时', 'D. 越久越好'],
    answer: 'B',
    difficulty: 1,
    explanation: '成年人每天7-8小时睡眠最有利于身体恢复和大脑功能，过少或过多都不健康。',
  },
  {
    id: 'fb-05',
    question: '银行卡密码设置最安全的是？',
    options: ['A. 生日日期', 'B. 123456', 'C. 无规律随机数字', 'D. 手机号后6位'],
    answer: 'C',
    difficulty: 1,
    explanation: '无规律随机数字最安全。生日、手机号等个人信息容易被别人猜到。',
  },
  {
    id: 'fb-06',
    question: '吃完饭后多久刷牙最合适？',
    options: ['A. 立即刷牙', 'B. 半小时后', 'C. 2小时后', 'D. 饭前刷就行'],
    answer: 'B',
    difficulty: 3,
    explanation: '饭后口腔呈酸性，立即刷牙会损伤牙釉质。建议等半小时口腔酸碱度恢复后再刷。',
  },
  {
    id: 'fb-07',
    question: '哪种做法最能节省家庭用电？',
    options: ['A. 频繁开关灯', 'B. 将空调温度设为26°C', 'C. 电器长期待机', 'D. 冰箱塞满不留空隙'],
    answer: 'B',
    difficulty: 2,
    explanation: '空调设为26°C是最节能的制冷温度。频繁开关反而耗电，电器待机也耗电，冰箱过满影响制冷效率。',
  },
  {
    id: 'fb-08',
    question: '运动时脚崴了（踝关节扭伤），第一时间应该？',
    options: ['A. 热毛巾敷', 'B. 马上按摩揉搓', 'C. 冰敷并抬高', 'D. 继续坚持运动'],
    answer: 'C',
    difficulty: 2,
    explanation: '急性扭伤应遵循RICE原则：休息(Rest)、冰敷(Ice)、加压(Compression)、抬高(Elevation)。24-48小时内忌热敷。',
  },
  {
    id: 'fb-09',
    question: '以下哪种饮用水方式最健康？',
    options: ['A. 只喝纯净水', 'B. 每天喝足量白开水', 'C. 渴了才喝水', 'D. 用饮料代替水'],
    answer: 'B',
    difficulty: 1,
    explanation: '每天喝足量白开水（约1500-2000ml）最健康。纯净水缺乏矿物质，渴了才喝说明已缺水，饮料含糖不宜替代水。',
  },
  {
    id: 'fb-10',
    question: '收到陌生中奖短信链接，应该怎么办？',
    options: ['A. 点击链接查看详情', 'B. 按提示填写个人信息', 'C. 忽略并删除', 'D. 回复短信询问'],
    answer: 'C',
    difficulty: 1,
    explanation: '陌生中奖短信多为诈骗，点击链接可能泄露信息或感染病毒。应直接忽略删除。',
  },
  {
    id: 'fb-11',
    question: '使用微波炉加热食物，哪种容器最安全？',
    options: ['A. 金属碗', 'B. 普通塑料袋', 'C. 陶瓷碗', 'D. 一次性泡沫餐盒'],
    answer: 'C',
    difficulty: 2,
    explanation: '陶瓷碗安全。金属会引发火花，普通塑料和泡沫加热会释放有毒物质，需用微波炉专用容器。',
  },
  {
    id: 'fb-12',
    question: '垃圾分类中，过期药品属于哪类？',
    options: ['A. 可回收物', 'B. 厨余垃圾', 'C. 有害垃圾', 'D. 其他垃圾'],
    answer: 'C',
    difficulty: 2,
    explanation: '过期药品含有害化学成分，属于有害垃圾，不能随意丢弃以免污染环境。',
  },
  {
    id: 'fb-13',
    question: '电脑突然蓝屏，最应该先做什么？',
    options: ['A. 狂按键盘恢复', 'B. 记下错误代码后重启', 'C. 立刻拔电源', 'D. 拍打电脑主机'],
    answer: 'B',
    difficulty: 2,
    explanation: '记下蓝屏错误代码有助于诊断问题。直接拔电源可能损坏硬盘，应正常重启。',
  },
  {
    id: 'fb-14',
    question: '以下哪种做法最容易伤胃？',
    options: ['A. 少量多餐', 'B. 长期不吃早餐', 'C. 细嚼慢咽', 'D. 饭后散步'],
    answer: 'B',
    difficulty: 2,
    explanation: '长期不吃早餐会导致胃酸直接侵蚀胃黏膜，是胃炎、胃溃疡的重要诱因。',
  },
  {
    id: 'fb-15',
    question: '乘坐网约车时，为了安全应该？',
    options: ['A. 上车前不核对车牌', 'B. 将行程信息分享给亲友', 'C. 坐副驾驶位', 'D. 上车后关闭手机'],
    answer: 'B',
    difficulty: 1,
    explanation: '将行程分享给亲友是最重要的安全习惯。同时应核对车牌、坐后排并保持手机畅通。',
  },
  {
    id: 'fb-16',
    question: '哪种食品保存方法不科学？',
    options: ['A. 肉类冷冻保存', 'B. 剩菜趁热放入冰箱', 'C. 干货密封保存', 'D. 绿叶菜冷藏保存'],
    answer: 'B',
    difficulty: 3,
    explanation: '剩菜应放凉后(不超2小时)再进冰箱。热菜直接放入会升高冰箱温度，影响其他食物保鲜，也增加能耗。',
  },
  {
    id: 'fb-17',
    question: '面试时以下哪种行为最加分？',
    options: ['A. 迟到以显忙碌', 'B. 对前公司大肆批评', 'C. 提前了解公司背景并提问', 'D. 薪资要求越高越好'],
    answer: 'C',
    difficulty: 2,
    explanation: '提前了解公司背景并准备有深度的问题，展现诚意和职业素养，是面试加分项。',
  },
  {
    id: 'fb-18',
    question: '长期使用耳机对听力有损害，正确的做法是？',
    options: ['A. 音量开最大沉浸体验', 'B. 遵循60-60原则', 'C. 睡觉也戴着耳机', 'D. 只用一只耳朵听'],
    answer: 'B',
    difficulty: 2,
    explanation: '60-60原则：音量不超过最大音量的60%，每次使用不超过60分钟。能有效保护听力。',
  },
  {
    id: 'fb-19',
    question: '网上购物收到瑕疵商品，首先该怎么做？',
    options: ['A. 直接给差评', 'B. 拍照留证后联系卖家', 'C. 自行修理', 'D. 扔掉重买'],
    answer: 'B',
    difficulty: 1,
    explanation: '拍照留证后联系卖家协商退换或补偿。如卖家不配合，可申请平台介入或12315投诉。',
  },
  {
    id: 'fb-20',
    question: '哪种天气最适合户外运动？',
    options: ['A. 大雾霾天', 'B. 雷暴天气', 'C. 晴天气温适宜', 'D. 大风沙尘天'],
    answer: 'C',
    difficulty: 1,
    explanation: '晴朗、气温适宜、空气质量好的天气最适合户外运动。雾霾天伤肺，雷暴天危险，大风天容易着凉。',
  },
];
